# ./fly.toml (in the project root)

app = 'ai-data-analyst-backend-app'
primary_region = 'ams'

[build]

# This was [http_service] before, now we use [services] for more control
[services]
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1