# ./fly.toml (in the project root)

app = 'ai-data-analyst-backend-app'
primary_region = 'ams'

[build]

# This section tells Fly to forward traffic from its edge (ports 80/443)
# to port 8000 inside your application's VM.
[services]
  internal_port = 8000 # This was the missing line
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1