"""
Workflow State Management for LangGraph-based Data Analysis

This module defines the state structure and management for the data analysis workflow.
The state tracks the complete lifecycle from file upload through final response.
"""

from typing import Dict, Any, List, Optional, TypedDict
from enum import Enum
import time
from datetime import datetime


class NodeStatus(str, Enum):
    """Status of individual workflow nodes"""

    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class WorkflowState(TypedDict):
    """
    Complete state for the LangGraph data analysis workflow

    This state is passed between all nodes and tracks the entire workflow execution.
    Based on your workflow: upload → process → profile → query analysis → plan → execute → respond
    """

    # Session & Request Information
    session_id: str
    query: str
    llm_provider: str
    max_retries: int
    created_at: float

    # File & Data Information
    original_filename: str
    file_path: str
    parquet_path: str
    file_size: int

    # Data Processing Results (from data_processing node)
    raw_data_info: Optional[Dict[str, Any]]
    cleaned_data_info: Optional[Dict[str, Any]]
    processing_applied: List[str]  # List of cleaning operations applied

    # Data Profiling Results (from data_profiling node)
    data_profile: Optional[Dict[str, Any]]  # Comprehensive data analysis
    metadata: Optional[Dict[str, Any]]  # Column types, nulls, etc
    sample_data: Optional[str]  # Anonymized sample for LLM context
    quality_metrics: Optional[Dict[str, float]]  # Data quality scores

    # Query Analysis Results (from query_analysis node)
    user_intent: Optional[str]  # Classified intent (statistical, visualization, etc)
    analysis_plan: Optional[Dict[str, Any]]  # Structured plan for analysis
    required_columns: Optional[List[str]]  # Columns needed for analysis
    analysis_type: Optional[str]  # Type of analysis to perform

    # Code Generation Results (from code_generation node)
    generated_code: Optional[str]  # Python code generated by LLM
    code_explanation: Optional[str]  # Explanation of the code logic
    estimated_execution_time: Optional[float]  # Predicted execution time

    # Code Execution Results (from code_execution node)
    execution_result: Optional[Dict[str, Any]]  # Results from code execution
    execution_output: Optional[str]  # Stdout from execution
    execution_error: Optional[str]  # Any execution errors
    execution_plots: List[str]  # Base64 encoded plots
    execution_time: Optional[float]  # Actual execution time

    # Response Formatting Results (from response_formatting node)
    final_response: Optional[str]  # Natural language response
    response_elements: Optional[List[Dict[str, Any]]]  # Structured response components
    insights: Optional[List[str]]  # Key insights extracted

    # Workflow State Management
    current_node: str
    nodes_completed: List[str]
    nodes_failed: List[str]
    retry_count: int
    error_count: int

    # Error Handling
    last_error: Optional[str]
    error_history: List[Dict[str, Any]]
    recovery_attempted: bool

    # Performance & Monitoring
    start_time: float
    end_time: Optional[float]
    total_processing_time: Optional[float]
    node_timings: Dict[str, float]
    memory_usage: Optional[Dict[str, float]]

    # Conversation Context (for follow-up queries)
    conversation_history: List[Dict[str, Any]]
    previous_analyses: List[str]  # Previous successful analysis types
    context_preserved: bool  # Whether context from previous queries is available


class WorkflowStateManager:
    """
    Manages workflow state creation, validation, and transitions
    """

    @staticmethod
    def create_initial_state(
        session_id: str,
        query: str,
        file_info: Dict[str, Any],
        llm_provider: str = "gemini",
        max_retries: int = 2,
        conversation_history: Optional[List[Dict[str, Any]]] = None,
    ) -> WorkflowState:
        """
        Create initial workflow state from upload and query

        Args:
            session_id: Unique session identifier
            query: User's question/request
            file_info: Information about uploaded file
            llm_provider: LLM provider to use
            max_retries: Maximum retry attempts
            conversation_history: Previous conversation context

        Returns:
            Initial WorkflowState ready for processing
        """
        current_time = time.time()

        return WorkflowState(
            # Session & Request Information
            session_id=session_id,
            query=query,
            llm_provider=llm_provider,
            max_retries=max_retries,
            created_at=current_time,
            # File & Data Information
            original_filename=file_info.get("original_name", ""),
            file_path=file_info.get("file_path", ""),
            parquet_path=file_info.get("parquet_path", ""),
            file_size=file_info.get("size_bytes", 0),
            # Data Processing Results (initialized as None)
            raw_data_info=None,
            cleaned_data_info=None,
            processing_applied=[],
            # Data Profiling Results (initialized as None)
            data_profile=None,
            metadata=None,
            sample_data=None,
            quality_metrics=None,
            # Query Analysis Results (initialized as None)
            user_intent=None,
            analysis_plan=None,
            required_columns=None,
            analysis_type=None,
            # Code Generation Results (initialized as None)
            generated_code=None,
            code_explanation=None,
            estimated_execution_time=None,
            # Code Execution Results (initialized as None)
            execution_result=None,
            execution_output=None,
            execution_error=None,
            execution_plots=[],
            execution_time=None,
            # Response Formatting Results (initialized as None)
            final_response=None,
            response_elements=None,
            insights=None,
            # Workflow State Management
            current_node="data_processing",
            nodes_completed=[],
            nodes_failed=[],
            retry_count=0,
            error_count=0,
            # Error Handling
            last_error=None,
            error_history=[],
            recovery_attempted=False,
            # Performance & Monitoring
            start_time=current_time,
            end_time=None,
            total_processing_time=None,
            node_timings={},
            memory_usage=None,
            # Conversation Context
            conversation_history=conversation_history or [],
            previous_analyses=[],
            context_preserved=bool(conversation_history),
        )

    @staticmethod
    def transition_to_node(state: WorkflowState, node_name: str) -> WorkflowState:
        """
        Transition workflow state to a new node

        Args:
            state: Current workflow state
            node_name: Name of the next node

        Returns:
            Updated workflow state
        """
        # Record completion of current node if not initial
        if (
            state["current_node"]
            and state["current_node"] not in state["nodes_completed"]
        ):
            state["nodes_completed"].append(state["current_node"])

        # Set new current node
        state["current_node"] = node_name

        return state

    @staticmethod
    def record_node_completion(
        state: WorkflowState,
        node_name: str,
        execution_time: float,
        results: Optional[Dict[str, Any]] = None,
    ) -> WorkflowState:
        """
        Record successful completion of a workflow node

        Args:
            state: Current workflow state
            node_name: Name of completed node
            execution_time: Time taken to execute node
            results: Optional results to merge into state

        Returns:
            Updated workflow state
        """
        # Record timing
        state["node_timings"][node_name] = execution_time

        # Mark as completed
        if node_name not in state["nodes_completed"]:
            state["nodes_completed"].append(node_name)

        # Ensure not in failed list
        if node_name in state["nodes_failed"]:
            state["nodes_failed"].remove(node_name)

        # Merge results if provided
        if results:
            for key, value in results.items():
                if key in state:
                    state[key] = value

        return state

    @staticmethod
    def record_node_failure(
        state: WorkflowState, node_name: str, error: str, execution_time: float
    ) -> WorkflowState:
        """
        Record failure of a workflow node

        Args:
            state: Current workflow state
            node_name: Name of failed node
            error: Error message
            execution_time: Time taken before failure

        Returns:
            Updated workflow state
        """
        # Record timing even for failures
        state["node_timings"][node_name] = execution_time

        # Mark as failed
        if node_name not in state["nodes_failed"]:
            state["nodes_failed"].append(node_name)

        # Remove from completed if present
        if node_name in state["nodes_completed"]:
            state["nodes_completed"].remove(node_name)

        # Record error
        state["last_error"] = error
        state["error_count"] += 1
        state["error_history"].append(
            {
                "node": node_name,
                "error": error,
                "timestamp": time.time(),
                "retry_count": state["retry_count"],
            }
        )

        return state

    @staticmethod
    def increment_retry(state: WorkflowState) -> WorkflowState:
        """
        Increment retry count for the workflow
        """
        state["retry_count"] += 1
        state["recovery_attempted"] = True
        return state

    @staticmethod
    def finalize_workflow(state: WorkflowState, success: bool) -> WorkflowState:
        """
        Finalize workflow execution

        Args:
            state: Current workflow state
            success: Whether workflow completed successfully

        Returns:
            Finalized workflow state
        """
        end_time = time.time()
        state["end_time"] = end_time
        state["total_processing_time"] = end_time - state["start_time"]

        # Clear current node since workflow is complete
        state["current_node"] = "completed" if success else "failed"

        return state

    @staticmethod
    def should_retry(state: WorkflowState) -> bool:
        """
        Determine if workflow should retry based on current state

        Returns:
            True if retry should be attempted
        """
        return (
            state["retry_count"] < state["max_retries"]
            and state["error_count"] > 0
            and not state.get("recovery_attempted", False)
        )

    @staticmethod
    def get_workflow_summary(state: WorkflowState) -> Dict[str, Any]:
        """
        Get a summary of the workflow execution

        Returns:
            Summary dictionary with key metrics
        """
        return {
            "session_id": state["session_id"],
            "query": state["query"],
            "status": state["current_node"],
            "success": state["current_node"] == "completed",
            "total_time": state.get("total_processing_time", 0),
            "nodes_completed": len(state["nodes_completed"]),
            "nodes_failed": len(state["nodes_failed"]),
            "retry_count": state["retry_count"],
            "error_count": state["error_count"],
            "has_results": bool(state.get("final_response")),
            "has_plots": len(state.get("execution_plots", [])) > 0,
            "processing_applied": state.get("processing_applied", []),
            "analysis_type": state.get("analysis_type"),
            "llm_provider": state["llm_provider"],
        }
