# Frontent/fly.toml

app = 'aidataanalyst'
primary_region = 'ams'

[build]
  [build.args] # <--- ADD THIS SECTION
    VITE_API_BASE_URL = "https://ai-data-analyst-backend-app.fly.dev"

[env]
  VITE_API_BASE_URL = 'https://ai-data-analyst-backend-app.fly.dev'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1